FROM golang:1.22.2-alpine3.18 AS builder

WORKDIR /app
COPY . ./
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -o app ./cmd/producerd/main.go

# Final image
FROM alpine:3.18 AS compile
COPY --from=builder /app .
CMD ["./app"]